import { apiDelete, apiGet, apiPatch, apiPost, apiPut } from './apiClient'

export const listIncidents = (params = {}) => apiGet('/api/incidents/', params)
export const createIncident = (payload) => apiPost('/api/incidents/', payload)
export const createV1Incident = (payload) => apiPost('/api/v1/incidents', payload)
export const updateIncident = (incidentId, payload) => apiPut(`/api/incidents/${incidentId}`, payload)
export const getDuplicateIncidents = () => apiGet('/api/v1/incidents/duplicates')
export const getIncidentQueue = () => apiGet('/api/v1/incidents/queue')
export const getIncidentById = (incidentId) => apiGet(`/api/v1/incidents/${incidentId}`)
export const setIncidentPriority = (incidentId, priority) => apiPost(`/api/v1/incidents/${incidentId}/priority`, { priority })
export const submitIncident = (incidentId) => apiPost(`/api/v1/incidents/${incidentId}/submit`, {})
export const addIncidentNote = (incidentId, note) => apiPost(`/api/v1/incidents/${incidentId}/notes`, { note })
export const getIncidentCalls = (incidentId) => apiGet(`/api/v1/incidents/${incidentId}/calls`)

export const listUnits = () => apiGet('/api/v1/units/live')
export const listCrewMembers = () => apiGet('/api/admin/crew')
export const listAmbulances = () => apiGet('/api/ambulances/')
export const createAmbulance = (payload) => apiPost('/api/ambulances/', payload)
export const updateAmbulance = (ambulanceId, payload) => apiPut(`/api/ambulances/${ambulanceId}`, payload)
export const patchAmbulanceTelemetry = (ambulanceId, telemetry) => apiPatch(`/api/ambulances/${ambulanceId}/telemetry`, telemetry)
export const getCurrentDispatchForUnit = (unitId) => apiGet(`/api/v1/units/${unitId}/dispatch/current`)

export const getDispatchBoard = () => apiGet('/api/dispatch/')
export const getDispatchRouteForAmbulance = (ambulanceId) => apiGet(`/api/dispatch/route/ambulance/${ambulanceId}`)
export const getDispatchRouteForIncident = (incidentId) => apiGet(`/api/dispatch/route/incident/${incidentId}`)
export const getDispatchRecommendation = (incidentId) => apiGet(`/api/dispatch/recommend/${incidentId}`)
export const createDispatch = (payload) => apiPost('/api/dispatch/dispatch', payload)
export const patchDispatch = (dispatchId, payload) => apiPatch(`/api/dispatch/${dispatchId}/status`, payload)
export const createV1Dispatch = (payload) => apiPost('/api/v1/dispatches', payload)
export const updateV1Dispatch = (dispatchId, payload) => apiPatch(`/api/v1/dispatches/${dispatchId}`, payload)
export const getDispatchEta = (dispatchId) => apiGet(`/api/v1/dispatches/${dispatchId}/eta`)
export const sendDispatchMessage = (dispatchId, payload) => apiPost(`/api/v1/dispatches/${dispatchId}/messages`, payload)
export const getNearestUnit = (payload) => apiPost('/api/v1/routing/nearest-unit', payload)
export const getRouteEta = (payload) => apiPost('/api/v1/routing/eta', payload)
export const getNavigation = (payload) => apiPost('/api/v1/routing/navigation', payload)
export const getDispatchRecommendationV1 = (incidentId) => apiGet(`/api/v1/incidents/${incidentId}/recommendation`)

export const listCalls = () => apiGet('/api/calls/')
export const createCall = (payload) => apiPost('/api/calls/', payload)
export const updateCall = (callId, payload) => apiPatch(`/api/calls/${callId}`, payload)
export const setCallLocation = (callId, payload) => apiPost(`/api/v1/calls/${callId}/location`, payload)
export const createV1Call = (payload) => apiPost('/api/v1/calls', payload)

export const listHospitals = () => apiGet('/api/hospitals/')
export const createHospital = (payload) => apiPost('/api/hospitals/', payload)
export const patchHospital = (hospitalId, payload) => apiPatch(`/api/hospitals/${hospitalId}`, payload)
export const getHospitalCapacity = (hospitalId) => apiGet(`/api/hospitals/${hospitalId}/capacity`)
export const updateHospitalCapacity = (hospitalId, payload) => apiPut(`/api/hospitals/${hospitalId}/capacity`, payload)
export const getHospitalCapacityBoard = () => apiGet('/api/v1/hospitals/capacity')
export const assignDestinationHospital = (dispatchId, payload) => apiPost(`/api/v1/dispatches/${dispatchId}/destination-hospital`, payload)
export const closeIncident = (incidentId, payload) => apiPost(`/api/v1/incidents/${incidentId}/closeout`, payload)
export const getHospitalInbound = (hospitalId) => apiGet(`/api/v1/hospitals/${hospitalId}/inbound`)
export const setHospitalCapacity = (hospitalId, payload) => apiPost(`/api/v1/hospitals/${hospitalId}/capacity`, payload)
export const acknowledgeInbound = (hospitalId, dispatchId) => apiPost(`/api/v1/hospitals/${hospitalId}/inbound/${dispatchId}/acknowledge`, {})

export const listPatients = () => apiGet('/api/patients/')
export const createPatient = (payload) => apiPost('/api/patients/', payload)
export const updatePatient = (patientId, payload) => apiPatch(`/api/patients/${patientId}`, payload)

export const createAssessment = (assignmentId, payload) => apiPost(`/api/assignments/${assignmentId}/assessments`, payload)
export const getAssessments = (assignmentId) => apiGet(`/api/assignments/${assignmentId}/assessments`)

export const getAdminStaff = () => apiGet('/api/admin/staff')
export const createAdminStaff = (payload) => apiPost('/api/admin/staff', payload)
export const getStations = () => apiGet('/api/v1/stations')
export const createStation = (payload) => apiPost('/api/v1/stations', payload)
export const getStationById = (stationId) => apiGet(`/api/v1/stations/${stationId}`)
export const updateStation = (stationId, payload) => apiPatch(`/api/v1/stations/${stationId}`, payload)
export const deleteStation = (stationId) => apiDelete(`/api/v1/stations/${stationId}`)
export const getUsers = () => apiGet('/api/v1/users')
export const createUser = (payload) => apiPost('/api/v1/users', payload)
export const getUserById = (userId) => apiGet(`/api/v1/users/${userId}`)
export const updateUser = (userId, payload) => apiPatch(`/api/v1/users/${userId}`, payload)
export const deleteUser = (userId) => apiDelete(`/api/v1/users/${userId}`)
export const getRoles = () => apiGet('/api/v1/roles')
export const createRole = (payload) => apiPost('/api/v1/roles', payload)
export const updateRole = (roleId, payload) => apiPatch(`/api/v1/roles/${roleId}`, payload)
export const getZones = () => apiGet('/api/v1/zones')
export const createZone = (payload) => apiPost('/api/v1/zones', payload)
export const getVehicles = () => apiGet('/api/v1/vehicles')
export const createVehicle = (payload) => apiPost('/api/v1/vehicles', payload)
export const updateVehicle = (vehicleId, payload) => apiPatch(`/api/v1/vehicles/${vehicleId}`, payload)
export const reallocateUnit = (unitId, payload) => apiPost(`/api/v1/units/${unitId}/reallocate`, payload)
export const getFleetDashboard = () => apiGet('/api/v1/dashboard/fleet')
export const getVehicleDiagnostics = (vehicleId) => apiGet(`/api/v1/vehicles/${vehicleId}/diagnostics`)
export const getVehicleAlerts = (vehicleId) => apiGet(`/api/v1/vehicles/${vehicleId}/alerts`)
export const createMaintenanceRecord = (vehicleId, payload) => apiPost(`/api/v1/vehicles/${vehicleId}/maintenance-records`, payload)
export const getMaintenanceRecords = (vehicleId) => apiGet(`/api/v1/vehicles/${vehicleId}/maintenance-records`)
export const setVehicleServiceStatus = (vehicleId, payload) => apiPost(`/api/v1/vehicles/${vehicleId}/service-status`, payload)
export const getVehicleUsage = (vehicleId) => apiGet(`/api/v1/vehicles/${vehicleId}/usage`)
export const getRosters = () => apiGet('/api/v1/rosters')
export const createRoster = (payload) => apiPost('/api/v1/rosters', payload)
export const updateRoster = (rosterId, payload) => apiPatch(`/api/v1/rosters/${rosterId}`, payload)
export const getStaffingCurrent = () => apiGet('/api/v1/staffing/current')
export const getPostIncidentReport = (incidentId) => apiGet(`/api/v1/reports/post-incident/${incidentId}`)
export const getZoneCoverageAlerts = () => apiGet('/api/v1/alerts/zone-coverage')
export const getAuditLog = () => apiGet('/api/v1/audit-log')
export const getOperationalReports = () => apiGet('/api/v1/reports/operational')
export const exportOperationalReports = () => apiGet('/api/v1/reports/operational/export')
export const getTriageProtocols = () => apiGet('/api/v1/protocols/triage')
export const patchTriageProtocols = (payload) => apiPatch('/api/v1/protocols/triage', payload)
export const getDispatchRecommendationProtocol = () => apiGet('/api/v1/protocols/dispatch-recommendation')
export const patchDispatchRecommendationProtocol = (payload) => apiPatch('/api/v1/protocols/dispatch-recommendation', payload)
