import { useMemo, useState } from 'react'
import { AlertTriangle, Battery, Car, CalendarDays, Search, Thermometer, Wrench } from 'lucide-react'
import ActionButton from '../../components/common/ActionButton'
import DataTable from '../../components/common/DataTable'
import MetricCard from '../../components/common/MetricCard'
import Panel from '../../components/common/Panel'
import StatusBadge from '../../components/common/StatusBadge'
import { useCad } from '../../context/CadContext'

export default function FleetMaintenance() {
  const { maintenance } = useCad()
  const [records, setRecords] = useState(maintenance)
  const [selectedId, setSelectedId] = useState(maintenance[0]?.id)
  const [query, setQuery] = useState('')
  const [filter, setFilter] = useState('ALL')
  const [feedback, setFeedback] = useState('')
  const selected = records.find((record) => record.id === selectedId) || records[0]
  const filtered = useMemo(() => records.filter((record) => (filter === 'ALL' || record.status === filter) && `${record.id} ${record.callSign} ${record.faults.join(' ')}`.toLowerCase().includes(query.toLowerCase())), [records, filter, query])
  const updateStatus = (status) => { setRecords((items) => items.map((record) => record.id === selected.id ? { ...record, status } : record)); setFeedback(`${selected.id} marked ${status}.`) }
  return <div className="grid h-full min-h-0 grid-cols-[minmax(0,1fr)_350px] grid-rows-[auto_minmax(0,1fr)] gap-3 p-4">
    <div className="col-span-2 grid grid-cols-5 gap-3"><MetricCard label="FLEET READY" value={`${records.filter((record) => record.status === 'IN SERVICE').length}/${records.length}`} icon={Car} tone="success" /><MetricCard label="ACTIVE FAULTS" value={records.filter((record) => record.faults.length).length} icon={AlertTriangle} tone="danger" /><MetricCard label="CRITICAL" value={records.filter((record) => record.status === 'CRITICAL').length} icon={AlertTriangle} tone="danger" /><MetricCard label="SERVICE DUE" value={records.filter((record) => record.oil === 'DUE' || record.status === 'MAINTENANCE').length} icon={CalendarDays} /><MetricCard label="CAN BUS" value="ONLINE" sub="Mock telemetry feed" icon={Battery} tone="success" /></div>
    <Panel title="VEHICLE STATUS" subtitle="CAN BUS DIAGNOSTICS · MOCK TELEMETRY" className="flex min-h-0 flex-col overflow-hidden"><div className="flex gap-2 border-b border-[#222B3A] p-3"><div className="relative flex-1"><Search size={14} className="absolute left-3 top-2.5 text-[#7E8A9A]" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search unit or DTC" className="cad-input h-9 py-1 pl-9 text-[11px]" /></div><select value={filter} onChange={(event) => setFilter(event.target.value)} className="cad-input h-9 w-32 py-1 text-[11px]"><option>ALL</option><option>IN SERVICE</option><option>WARNING</option><option>CRITICAL</option><option>MAINTENANCE</option><option>OUT OF SERVICE</option></select></div><div className="min-h-0 flex-1 overflow-auto"><DataTable rows={filtered} onRowClick={(record) => setSelectedId(record.id)} columns={[{ key: 'id', label: 'Unit' }, { key: 'mileage', label: 'Mileage' }, { key: 'temperature', label: 'Temp', render: (record) => <span className={record.temperature > 100 ? 'text-[#EF4444]' : ''}>{record.temperature}°C</span> }, { key: 'battery', label: 'Battery', render: (record) => `${record.battery}%` }, { key: 'faults', label: 'DTC / Faults', render: (record) => record.faults.join(', ') || '—' }, { key: 'status', label: 'Status', render: (record) => <StatusBadge status={record.status} /> }]} /></div></Panel>
    <aside className="flex min-h-0 flex-col gap-3"><Panel title={`VEHICLE HEALTH · ${selected?.id || '—'}`} className="shrink-0"><div className="p-3"><div className="grid grid-cols-2 gap-2"><Health icon={Thermometer} label="ENGINE TEMP" value={`${selected?.temperature}°C`} danger={selected?.temperature > 100} /><Health icon={Battery} label="BATTERY" value={`${selected?.battery}%`} danger={selected?.battery < 70} /></div><p className="mt-3 text-[11px] text-[#AAB4C3]">Oil: <b>{selected?.oil}</b> · Tires: <b>{selected?.tires}</b></p><p className="mt-2 flex items-center gap-2 text-[10px] text-[#7E8A9A]"><CalendarDays size={13} />Next service: {selected?.serviceDate}</p><div className="mt-3 grid grid-cols-2 gap-2"><ActionButton icon={Wrench} variant="danger" onClick={() => updateStatus('OUT OF SERVICE')}>OUT OF SERVICE</ActionButton><ActionButton icon={Car} onClick={() => updateStatus('IN SERVICE')}>RETURN TO SERVICE</ActionButton></div><ActionButton className="mt-2 w-full" variant="primary" onClick={() => updateStatus('MAINTENANCE')}>SCHEDULE MAINTENANCE</ActionButton>{feedback && <p className="mt-2 text-[10px] text-[#86EFAC]">{feedback}</p>}</div></Panel><Panel title="FAULT / DTC RECORD" className="min-h-0 flex-1 overflow-hidden"><div className="h-full overflow-y-auto p-3">{records.filter((record) => record.faults.length).map((record) => <button key={record.id} type="button" onClick={() => setSelectedId(record.id)} className="mb-2 w-full border border-[#222B3A] p-2 text-left hover:border-[#38BDF8]"><div className="flex justify-between text-[11px]"><b>{record.id}</b><StatusBadge status={record.status} /></div><p className="mt-1 text-[10px] text-[#AAB4C3]">{record.faults.join(' · ')}</p></button>)}</div></Panel></aside>
  </div>
}
function Health({ icon: Icon, label, value, danger }) { return <div className="border border-[#222B3A] bg-[#0F141D] p-2"><Icon size={14} className={danger ? 'text-[#EF4444]' : 'text-[#38BDF8]'} /><span className="mt-1 block text-[8px] tracking-wider text-[#7E8A9A]">{label}</span><b className={danger ? 'text-[#FCA5A5]' : ''}>{value}</b></div> }
