import { useMemo, useState } from 'react'
import { Download, FileText, Plus, ShieldCheck, Users } from 'lucide-react'
import ActionButton from '../../components/common/ActionButton'
import DataTable from '../../components/common/DataTable'
import Modal from '../../components/common/Modal'
import Panel from '../../components/common/Panel'
import SearchInput from '../../components/common/SearchInput'
import { useCad } from '../../context/CadContext'

export default function AdminDashboard() {
  const { users } = useCad()
  const [records, setRecords] = useState(users)
  const [query, setQuery] = useState('')
  const [role, setRole] = useState('ALL')
  const [modalOpen, setModalOpen] = useState(false)
  const [draft, setDraft] = useState({ name: '', role: 'Dispatcher', station: 'DISP-02' })
  const [feedback, setFeedback] = useState('')
  const roles = [...new Set(users.map((user) => user.role))]
  const visible = useMemo(() => records.filter((user) => (role === 'ALL' || user.role === role) && `${user.name} ${user.role} ${user.station}`.toLowerCase().includes(query.toLowerCase())), [records, query, role])
  const toggleStatus = (user) => { const status = user.status === 'ACTIVE' ? 'SUSPENDED' : 'ACTIVE'; setRecords((items) => items.map((item) => item.id === user.id ? { ...item, status } : item)); setFeedback(`${user.name} is now ${status}.`) }
  const createUser = () => { if (!draft.name.trim() || !draft.station.trim()) { setFeedback('Name and station are required.'); return }; const roleKey = draft.role.toLowerCase().replaceAll(' / ', '-').replaceAll(' ', '-'); setRecords((items) => [...items, { id: `USR-${String(items.length + 1).padStart(3, '0')}`, name: draft.name.trim(), role: draft.role, roleKey, station: draft.station.trim(), status: 'ACTIVE' }]); setModalOpen(false); setFeedback(`Created account for ${draft.name.trim()}.`); setDraft({ name: '', role: 'Dispatcher', station: 'DISP-02' }) }
  const audit = [{ id: 1, time: '2026-08-20 10:42', actor: 'Nadia Hassan', action: 'UPDATE', entity: 'USR-004' }, { id: 2, time: '2026-08-20 10:37', actor: 'Nadia Hassan', action: 'CREATE', entity: 'USR-007' }, { id: 3, time: '2026-08-20 10:31', actor: 'CAD System', action: 'REPORT', entity: 'OPS-DAILY' }]
  return <div className="grid h-full min-h-0 grid-cols-[minmax(0,1fr)_360px] grid-rows-[auto_minmax(0,1fr)] gap-3 p-4">
    <div className="col-span-2 grid grid-cols-3 gap-3"><Info icon={Users} label="USER ACCOUNTS" value={records.length} /><Info icon={ShieldCheck} label="ACTIVE ACCOUNTS" value={records.filter((user) => user.status === 'ACTIVE').length} /><Info icon={FileText} label="ROLES CONFIGURED" value={roles.length} /></div>
    <Panel title="USER MANAGEMENT" subtitle="Staff, roles, stations, and account status" actions={<ActionButton icon={Plus} variant="primary" onClick={() => setModalOpen(true)}>CREATE USER</ActionButton>} className="flex min-h-0 flex-col overflow-hidden"><div className="flex gap-2 border-b border-[#222B3A] p-3"><div className="max-w-sm flex-1"><SearchInput value={query} onChange={setQuery} placeholder="Search staff, role, or station" /></div><select value={role} onChange={(event) => setRole(event.target.value)} className="cad-input w-44 text-[11px]"><option>ALL</option>{roles.map((item) => <option key={item}>{item}</option>)}</select></div><div className="min-h-0 flex-1 overflow-auto"><DataTable rows={visible} columns={[{ key: 'id', label: 'ID' }, { key: 'name', label: 'Staff member' }, { key: 'role', label: 'Role' }, { key: 'station', label: 'Station' }, { key: 'status', label: 'Status', render: (user) => <span className={user.status === 'ACTIVE' ? 'text-[#86EFAC]' : 'text-[#FCA5A5]'}>{user.status}</span> }, { key: 'action', label: 'Action', render: (user) => <button type="button" onClick={(event) => { event.stopPropagation(); toggleStatus(user) }} className="text-[10px] font-bold text-[#38BDF8]">{user.status === 'ACTIVE' ? 'SUSPEND' : 'ACTIVATE'}</button> }]} /></div>{feedback && <div className="border-t border-[#222B3A] px-3 py-2 text-[10px] text-[#86EFAC]">{feedback}</div>}</Panel>
    <aside className="flex min-h-0 flex-col gap-3"><Panel title="AUDIT LOG" subtitle="Administrative mock events" className="flex min-h-0 flex-1 flex-col overflow-hidden"><div className="min-h-0 flex-1 overflow-auto"><DataTable rows={audit} columns={[{ key: 'time', label: 'Time' }, { key: 'actor', label: 'Actor' }, { key: 'action', label: 'Action' }, { key: 'entity', label: 'Entity' }]} /></div></Panel><Panel title="OPERATIONAL REPORTS" className="shrink-0"><div className="grid grid-cols-3 gap-2 p-3">{['Response Time', 'Incident Volume', 'Unit Use'].map((report) => <button key={report} type="button" onClick={() => setFeedback(`${report} report queued for export.`)} className="border border-[#222B3A] bg-[#0F141D] p-2 text-left text-[9px] hover:border-[#38BDF8]"><FileText size={13} className="text-[#38BDF8]" /><span className="mt-2 block">{report}</span></button>)}</div><div className="flex gap-2 px-3 pb-3"><ActionButton icon={Download} onClick={() => setFeedback('CSV export prepared in mock mode.')}>CSV</ActionButton><ActionButton icon={Download} onClick={() => setFeedback('PDF export prepared in mock mode.')}>PDF</ActionButton></div></Panel></aside>
    <Modal open={modalOpen} onClose={() => setModalOpen(false)} title="CREATE USER ACCOUNT"><div className="space-y-3"><label><span className="cad-label">NAME</span><input value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} className="cad-input" /></label><label><span className="cad-label">ROLE</span><select value={draft.role} onChange={(event) => setDraft({ ...draft, role: event.target.value })} className="cad-input">{roles.map((item) => <option key={item}>{item}</option>)}</select></label><label><span className="cad-label">STATION</span><input value={draft.station} onChange={(event) => setDraft({ ...draft, station: event.target.value })} className="cad-input" /></label><ActionButton variant="primary" className="w-full" onClick={createUser}>CREATE ACCOUNT</ActionButton></div></Modal>
  </div>
}
function Info({ icon: Icon, label, value }) { return <div className="cad-panel flex items-center justify-between p-3"><div><p className="text-[10px] tracking-wider text-[#7E8A9A]">{label}</p><b className="mt-1 block text-2xl">{value}</b></div><Icon className="text-[#38BDF8]" size={18} /></div> }
